name: ml-env
dependencies:
  - python=3.12.11
  - pip=25.2
  - ipykernel=6.30.1
  - jupyter=1.1.1
  - pandas=2.3.2
  - numpy=1.26.4
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - plotly=6.3.0
  - keras=3.11.2
  - keras-tuner=1.4.7
  - tensorboard=2.18.0
  - scikit-learn=1.7.1
  - python-dotenv=1.1.0